name: Install

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: install liburing-dev
        run: |
          sudo apt-get update
          sudo apt-get -y install liburing-dev

      - name: build and install everything
        run: |
          cmake -S ./all -Bbuild -DCMAKE_BUILD_TYPE=Release --log-level=DEBUG
          cmake --build build --target all --verbose -j $(nproc)
          cmake --install build --prefix ./install_dir
          rm -rf build

      - name: configure
        run: CMAKE_PREFIX_PATH="./install_dir" cmake -Stest -Bbuild -DTEST_INSTALLED_VERSION=1 -DCPM_DOWNLOAD_ALL=1 -DCPM_SOURCE_CACHE=~/.cache/cpm --log-level=DEBUG

      - name: build
        run: cmake --build build --config Debug -j $(nproc) --verbose

      - name: test
        run: |
          cd build
          ctest --build-config Debug -j $(nproc)
